# enable ES6
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  allowImportExportEverywhere: true

# register plugins
plugins:
  - meteor
  - i18next

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb-base
  - plugin:meteor/recommended

# registerenvironments
env:
  meteor: true
  browser: true
  node: true

settings:
  import/resolver: "meteor"

rules:
  # overwrite some rules (avoid semicolons)
  semi: [2, 'never']
  no-unexpected-multiline: 2
  no-underscore-dangle: ['error', { allow: ['_id']}]
  no-throw-literal: 0
  new-cap: 1
  object-shorthand: 1
  import/no-extraneous-dependencies: 0
  import/no-unresolved: [2, { ignore: ['^meteor'] }]
  no-console: [2, { allow: ['warn', 'error'] }]
  no-restricted-syntax: [2, 'DebuggerStatement', 'LabeledStatement', 'WithStatement']
  i18next/no-literal-string: 1
  # eslint-plugin-meteor
  # meteor/no-session: [1] # allow Session
  # meteor/prefer-session-equals: [2] # prefer Session.equals instead
  import/extensions: 0

globals:
  adsbygoogle: true
  # collections
