on:
  push:
    branches:
    - master
name: Docker build
jobs:
  release:
    name: Autotag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: autotag
        id: autotag
        uses: butlerlogic/action-autotag@1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          strategy: package
          tag_message: ${{ github.event.head_commit.message }}
      - name: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@latest
        if: success()
        with:
          tag_name: ${{steps.autotag.outputs.tagname}}
          release_name: ${{steps.autotag.outputs.tagname}}
          body: ${{steps.autotag.outputs.tagmessage}}
          draft: false
          prerelease: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: kromit/titra:latest, kromit/titra:${{steps.autotag.outputs.tagname}}
