on:
  push:
    branches:
    - master
name: automatically tag pushes and create releases
jobs:
  autotag:
    name: Autotag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: butlerlogic/action-autotag@1.0.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
